### PR TITLE
Add scope manager support

### LINKED ISSUE #54: Add support for scope manager
`opentracing==2.0` introduced scope manager API. The tracer is responsible for `scope_manager` implementation.

The order for detecting parent spans needs to be updated. I suggest one of the following two orders:

### Scope manager first

  1. Using ``opentracing.tracer.active_span`` managed by the tracer context manager. The new span will be using the
  scope manager.
  2. Using ``span_extractor``.
  3. Detecting span in kwargs.
  4. Using call stack frames inspection.

### Explicit first

  1. Using ``span_extractor``.
  2. Detecting span in kwargs.
  3. Using ``opentracing.tracer.active_span`` managed by the tracer context manager. The new span will be using the
  scope manager.
  4. Using call stack frames inspection.

as ``span_extractor`` and passing spans in ``kwargs`` is more explicit.

### PR DESCRIPTION
**Pull request by mohabusama**
Resolve #54
 
# Changes

Add support for tracer scope manager support introduced in `opentracing==2.0`.

I am not fully decided on the order of detecting parent spans. 
The proposed implementation is the following:

~1. Using ``opentracing.tracer.active_span`` managed by the tracer context manager. The new span will be using the
  scope manager.~
~2. Using ``span_extractor``.~
~3. Detecting span in kwargs.~
~4. Using call stack frames inspection.~

  1. Using ``span_extractor``.
  2. Detecting span in kwargs.
  3. Using ``opentracing.tracer.active_span`` managed by the tracer context manager. The new span will be using the
  scope manager.
  4. Using call stack frames inspection.

as ``span_extractor`` and passing spans in ``kwargs`` is more explicit.

Please let me know what you think.

# Release strategy

We don't have to release a new version right away after merging. We are planning to first test the changes in our production systems, fix any related bugs observed and confirm that no breaking changes are introduced.

### CODE REVIEW

**Comment by mohabusama** [comment]
@vetinari @pitr @dneuhaeuser-zalando Please let me know what you think.

**Comment by dneuhaeuser-zalando** [comment]
> It could be useful if we change to the following order: [...] as span_extractor and passing spans in kwargs is more explicit.

Agreed. Using span_extractor or passing a span clearly and explicitly communicates what the user wishes to happen in that specific location. I think that should override a scope or at the very least lead to a warning.

**Comment by mohabusama** [comment]
@mvalkon you might be interested in this one.

**Comment by mohabusama** [comment]
@vetinari @pitr this one is ready, we have tested it in production.

**Comment by mohabusama** [comment]
👍

**Comment by pitr** [comment]
👍

**Pull request merged**
